### ISSUE TITLE
Add "Make your space Night" to email reminders

### ISSUE THREAD

**Issue by zo0o0ot** [appletonmakerspace/emaildhmn#1]
Per Sim:

Hey DHMN Robot, can we get the public “Make the Space” night posted for Mondays at 6pm too?

**Comment by zo0o0ot** [comment]
BTW, I may need a remedial lesson in forking.  I was forking from the web client to make this change, and it didn't let me make a new fork because I have [emailnewlug](https://github.com/zo0o0ot/emailnewlug) as an existing fork to the code.

**Comment by mikeputnam** [comment]
Apparently Github doesn't provide it's front-end niceties for multiple same-forks.  Here is an example of manually arriving at multiple forks. https://adrianshort.org/create-multiple-forks-of-a-github-repo/

In my opinion however, unless your plans are to have multiple different codebases all possibly contributing back upstream(seems unlikely) you could achieve a similar outcome with your single fork just using long-lived branches(newlug-branch/feature-x-branch/etc) or separate repo clones(not on Github; just plain git)
